[package]
name = "peaq-rpc-core-debug"
authors = ['peaq network <https://github.com/peaqnetwork>']
edition = "2021"
homepage = 'https://peaq.network/'
license = "GPL-3.0-only"
repository = 'https://github.com/peaqnetwork/peaq-network-node/'
version = "0.1.0"

[dependencies]
ethereum-types = { workspace = true, default-features = true }
serde = { workspace = true, default-features = true, features = ["derive"] }
serde_json = { workspace = true, default-features = true }
futures = { workspace = true, default-features = true, features = ["compat"] }
jsonrpsee = { workspace = true, default-features = false, features = ["macros", "server"] }

peaq-client-evm-tracing = { path = "../../evm-tracing" }
peaq-rpc-core-types = { path = "../types" }

sp-core = { workspace = true, default-features = true }
