[package]
name = "peaq-rpc-core-txpool"
authors = ['peaq network <https://github.com/peaqnetwork>']
edition = "2021"
homepage = 'https://peaq.network/'
license = "GPL-3.0-only"
repository = 'https://github.com/peaqnetwork/peaq-network-node/'
version = "0.6.0"

[dependencies]
ethereum-types = { workspace = true, default-features = true }
serde = { workspace = true, default-features = true, features = ["derive"] }
serde_json = { workspace = true, default-features = true }

ethereum = { workspace = true, default-features = true, features = [ "with-codec" ] }
jsonrpsee = { workspace = true, default-features = true, features = [ "macros", "server" ] }

fc-rpc-core = { workspace = true, default-features = true }
