[package]
name = "peaq-rpc-txpool"
authors = ['peaq network <https://github.com/peaqnetwork>']
edition = "2021"
homepage = 'https://peaq.network/'
license = "GPL-3.0-only"
repository = 'https://github.com/peaqnetwork/peaq-network-node/'
version = "0.6.0"

[dependencies]
jsonrpsee = { workspace = true, default-features = true, features = [ "macros", "server" ] }
rlp = { workspace = true, default-features = true }
serde = { workspace = true, default-features = true, features = [ "derive" ] }
sha3 = { workspace = true, default-features = true }

peaq-rpc-core-txpool = { path = "../../rpc-core/txpool" }
peaq-rpc-primitives-txpool = { path = "../../../primitives/rpc/txpool" }

# Substrate
frame-system = { workspace = true, default-features = true }
sc-transaction-pool = { workspace = true, default-features = true }
sc-transaction-pool-api = { workspace = true, default-features = true }
sp-api = { workspace = true, default-features = true }
sp-blockchain = { workspace = true, default-features = true }
sp-io = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }
sp-std = { workspace = true, default-features = true }

# Frontier
ethereum-types = { workspace = true, default-features = true }
fc-rpc = { workspace = true, default-features = true }
