
name: Pull Request Check & Build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed

jobs:
  check:
    runs-on: ubuntu-20.04

    steps:
      - name: "[Setup] Free Disk Space (insightsengineering/disk-space-reclaimer)"
        uses: insightsengineering/disk-space-reclaimer@v1.1.0

      - name: "[Setup] Linux Tools"
        run: sudo apt install -y cmake pkg-config libssl-dev build-essential clang libclang-dev curl protobuf-compiler

      - name: Install Rustup
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source ~/.cargo/env
          # rustup default stable
          rustup update nightly
          # rustup update stable
          rustup target add wasm32-unknown-unknown --toolchain nightly
          rustup component add rustfmt --toolchain nightly
          cargo install cargo-expand --locked --version 1.0.34

      - name: Checkout Sources (actions/checkout)
        uses: actions/checkout@v3

      - name: "[Ceck] cargo fmt"
        run: |
          cargo fmt --check

      - name: "[Check] cargo clippy"
        run: |
          cargo clippy --release -- -Dwarnings

      - name: "[Check] cargo test"
        run: |
          SKIP_WASM_BUILD=1 cargo test --release
