
name: Pull Request Check & Build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed

jobs:
  check:
    runs-on: ubuntu-20.04

    steps:
      - name: Setup, Free Disk Space (insightsengineering/disk-space-reclaimer)
        uses: insightsengineering/disk-space-reclaimer@v1.1.0

      - name: Setup, Linux Tools
        run: sudo apt install -y cmake pkg-config libssl-dev build-essential clang libclang-dev curl protobuf-compiler

      - name: Setup, Rust (ATiltedTree/setup-rust)
        uses: ATiltedTree/setup-rust@v1.0.5
        with:
          rust-version: nightly-2022-11-03
          components: clippy
          targets: wasm32-unknown-unknown

      - name: Checkout Sources (actions/checkout)
        uses: actions/checkout@v3

      - name: Ceck, cargo fmt
        run: |
          cargo fmt --check

      - name: Check, cargo clippy
        run: |
          cargo clippy --release -- -Dwarnings

      # - name: Check, cargo check
      #   run: |
      #     SKIP_WASM_BUILD=1 cargo check --release

      - name: Check, cargo test
        run: |
          SKIP_WASM_BUILD=1 cargo test --release
