
name: Pull Request Check & Build

# Controls when the action will run.
on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Disk Space Reclaimer
        uses: insightsengineering/disk-space-reclaimer@v1.1.0

      - name: Install Linux Tools
        run: sudo apt install -y cmake pkg-config libssl-dev build-essential clang libclang-dev curl protobuf-compiler

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
          rustup target add wasm32-unknown-unknown --toolchain nightly
          rustup component add rustfmt --toolchain nightly
          rustup component add clippy --toolchain nightly
          cargo install cargo-expand --locked --version 1.0.34

      - name: Run cargo fmt
        run: |
          cargo fmt --check

      - name: Run cargo clippy
        run: |
          cargo clippy -- -Dwarnings

      - name: Run Cargo check
        run: |
          SKIP_WASM_BUILD=1 cargo check --release

      - name: Run cargo test
        run: |
          SKIP_WASM_BUILD=1 cargo test --release
