name: Deploy to Remote Server

on:
  push:
    branches:
      - add/1205782676034164_autotest-deplyoment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AUTOTEST_HOST }}
          username: ${{ secrets.AUTOTEST_USERNAME }}
          key: ${{ secrets.SSH_KEY_AUTOTEST }}
          port: ${{ secrets.AUTOTEST_SSH_PORT }}
          script: |
            cd /home/jay/parachain-launch/yoyo/
            sudo TAG=krest-v0.0.4 docker compose down -v
            sudo TAG=krest-v0.0.4 docker compose up -d --build --remove-orphans
